version: 2.1
orbs:
  sonarscanner: psl/sonarscanner@0.0.4
jobs:
  test:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Install Nodejs
          command: |
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - sonarscanner/check-code-quality:
          sonar_server_url: $SONARQUBE_URL
          sonar_login: $SONARQUBE_TOKEN
          sonar_sources: .

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
     IMAGE_NAME: omarsayed/work  
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t omarsayed/work:latest .
            docker login -u omarsayed -p $DOCKERHUB_PASSWORD
            docker push omarsayed/work:latest
            
      - add_ssh_keys:
          fingerprints:
            - "e7:b8:5d:56:0a:bc:3e:47:11:39:56:ed:1d:ca:a2:2f"
      - run:
          name: Deploy docker image
          command: |
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker login -u omarsayed -p $DOCKERHUB_PASSWORD"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker stop omar-app || true && docker rm omar-app || true"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker run -d --name omar-app \
            --network mongodb_default \
            omarsayed/work:latest"                  
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
      - build
          requires:
            - test
