version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
     IMAGE_NAME: omarsayed/work  
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t omarsayed/work:latest .
            docker login -u omarsayed -p $DOCKERHUB_PASSWORD
            docker push omarsayed/work:latest
            
      - add_ssh_keys:
          fingerprints:
            - "e7:b8:5d:56:0a:bc:3e:47:11:39:56:ed:1d:ca:a2:2f"
      - run:
          name: Deploy docker image
          command: |
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker login -u omarsayed -p $DOCKERHUB_PASSWORD"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker stop omar-app || true && docker rm omar-app || true"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker run -d --name omar-app \
            --network mongodb_default \
            omarsayed/work:latest"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "
             docker run \
             --rm \
             -e SONAR_HOST_URL="https://sonar-test.code95.info" \
             -e SONAR_LOGIN="b07435ad10bf9dee60e24d6be906eb8744e635e9" \
             -v "https://github.com/omarsayed43/-Node.js-Expess-MongoDB-CRUD:/usr/src" \
             sonarsource/sonar-scanner-cli"
workflows:
  version: 2
  build-main:
    jobs:
      - build
