version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
     IMAGE_NAME: omarsayed/work  
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t omarsayed/work:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u omarsayed --password-stdin
            docker push omarsayed/work:latest
            
      - add_ssh_keys:
          fingerprints:
            - "c0:62:a1:78:31:cd:3d:c2:d0:a4:84:c8:3d:22:32:59"
      - run:
          name: Deploy docker image
          command: |
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker login -u omarsayed -p $DOCKERHUB_PASSWORD"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker stop omar-app || true && docker rm omar-app || true"
            ssh -o StrictHostKeyChecking=no omar@169.50.178.238 -p 9621 "docker run -d --name omar-app --network mongodb_default omarsayed/work:latest "            
        
workflows:
  version: 2
  build-main:
    jobs:
      - build
